#Gitlab CI script for firebase and react;
#Sonar token for gitlab_ci: 7fc29f63fc7c8bf8caba011fe8021e2c5a2f94d2
image: node:latest                #for node applications

stages:
  - test
  - quality
  - deploy

framework-test:
  stage: test
  only:
    - desenvolvimento
    - master
  script:
    - npm install -g codecov
    - npm install
    - npm run test
    - codecov --token=: $CODECOV_TOKEN

sonar-scanner:
  stage: quality
  only:
    - desenvolvimento
    - master
  script:
    - npm install
    - npm install -g sonarqube-scanner
    - npm run build
    - sonar-scanner -Dsonar.projectKey=retomada_web -Dsonar.sources=. -Dsonar.host.url=https://sonar.winstonsec.com -Dsonar.login=7fc29f63fc7c8bf8caba011fe8021e2c5a2f94d2

deploy-prod:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm install -g firebase-tools
    - npm run build
    - firebase use $FIREBASE_PROJECT --token $FIREBASE_TOKEN
    - firebase deploy --token $FIREBASE_TOKEN
